# SPDX-FileCopyrightText: Copyright 2025 New Vector Ltd.
#
# SPDX-License-Identifier: AGPL-3.0-only OR LicenseRef-Element-Commercial

version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    labels:
      - "A-Dependencies"
    schedule:
      interval: "daily"

  - package-ecosystem: "npm"
    directory: "/"
    labels:
      - "A-Dependencies"
    schedule:
      interval: "daily"
    groups:
      fontsource:
        patterns:
          - "@fontsource/*"
      vite:
        patterns:
          - "vite"
          - "@vitejs/*"
          - "vite-*"
      eslint:
        patterns:
          - "eslint"
          - "eslint-*"
          - "@eslint/*"
      stylelint:
        patterns:
          - "stylelint"
          - "stylelint-*"
      react:
        patterns:
          - "react"
          - "react-*"
        exclude-patterns:
          - "react-i18next"
      tanstack-router:
        patterns:
          - "@tanstack/react-router*"
          - "@tanstack/router*"
          - "@tanstack/eslint-plugin-router"
      tanstack-query:
        patterns:
          - "@tanstack/react-query*"
          - "@tanstack/query*"
          - "@tanstack/eslint-plugin-query"
      tanstack-pacer:
        patterns:
          - "@tanstack/react-pacer*"
          - "@tanstack/parce*"
      tanstack-devtools:
        patterns:
          - "@tanstack/react-devtools*"
          - "@tanstack/devtools*"
      types:
        patterns:
          - "@types/*"
